#+title: Research Notes
* Date
** Pixels
** Disappearing Tracks
** MilliQan
* 9/21/22
** pixels
** disappearing tracks
*** i believe the issue is with the way that i created the npz files. after evaluating on the old datasets, everything seemed fine.

** milliqan

* 9/23/22
** pixels
** disappearing tracks
*** The bad performance of the classifier is due to the format of the dataset.
**** Evaluating on the original data ( not the electron data that I needed to remove the pdgid selection for) the numbers seem reasonable.
**** If the training data is not the same as what I'm evaluating on, and I can evaluate over both the higgsino and electron datasets with both the classifier and map, I should be fine.
** milliqan
* 9/25/22
** Disappearing Tracks
*** I need to re-evaluate the fiducial map on the new set of data.
**** I believe that the only thing that I need to change is the condor script
**** The way that the condor job is created, it only saves the file number, so I couldn't just loop over the multiple directories, to do this without changing the code I need to just run this multiple times
**** Actually don't need to do this because I did it before
