#+title: Research Notes
* Date
** Pixels
** Disappearing Tracks
** MilliQan
* 9/21/22
** pixels
** disappearing tracks
*** i believe the issue is with the way that i created the npz files. after evaluating on the old datasets, everything seemed fine.

** milliqan

* 9/23/22
** pixels
** disappearing tracks
*** The bad performance of the classifier is due to the format of the dataset.
**** Evaluating on the original data ( not the electron data that I needed to remove the pdgid selection for) the numbers seem reasonable.
**** If the training data is not the same as what I'm evaluating on, and I can evaluate over both the higgsino and electron datasets with both the classifier and map, I should be fine.
** milliqan
* 9/25/22
** Disappearing Tracks
*** I need to re-evaluate the fiducial map on the new set of data.
**** I believe that the only thing that I need to change is the condor script
**** The way that the condor job is created, it only saves the file number, so I couldn't just loop over the multiple directories, to do this without changing the code I need to just run this multiple times
**** Actually don't need to do this because I did it before
* 9/26/22
** Disappearing Tracks
*** The fiducial maps have really bad precision, I need to debug what is going on here.
**** At 0 sigma, I believe there should be no TN or FN ( everywhere should be a hotspot, so nothing can fall outside of it)
***** The data is showing that there are 0 false negatives, but it says there are still true negatives.
**** I believe that the classifier is more or less working fine, I need to fix the fiducial map issues though.
** Pixels
*** I need to add the peltier controller to the main GUI.
**** Hopefully PyQt does some magic and fits everything correctly, otherwise I will need to resize the GUI
**** It does do magic!
*** There is a large textbox that flows through the Peltier controller, I should try and put in a group box to seperate the two.
*** The temperature reader also looks janky because it is too big.
